### ISSUE TITLE
USB: only open boards that are needed

### ISSUE THREAD

**Issue by paulbartell** [uw-biorobotics/raven2#11]
Currently all available brl_usb\* board files are opened during USBInit in USB_init.cpp rather than just those defined for the current robot. This could cause unwanted issues when using other usb boards on the same computer.

**Comment by awlewi** [comment]
This remains an open project, but the latest release will include code for extra USB boards for external joint encoders. Future releases will include support for at least 3 arms and two encoder USB boards.
